---
- name: Include OS-specific variables
  ansible.builtin.include_vars: vars/main.yml

- name: Symlink Rime config for Unix-like systems (Linux, macOS)
  ansible.builtin.file:
    src: "{{ role_path }}/roles/rime/files/rime"
    dest: "{{ rime_destination_paths[ansible_system] }}"
    state: link
    force: true
  when: ansible_system in ['Linux', 'Darwin']

- name: Symlink Rime config for Windows
  ansible.windows.win_file:
    src: "{{ role_path }}/roles/rime/files/rime"
    dest: "{{ rime_destination_paths[ansible_os_family] }}"
    state: junction
  when: ansible_os_family == "Windows"
